apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-ratings
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.opsta.net/student124/ratings
maintainers:
  - name: student124
    email: devop124@mail.kmutt.ac.th
sources:
  - https://github.com/crisspina/bookinfo-ratings